## EJERCICIO 1: URBAN DEVELOPMENT CHILE

In [7]:
# librerias clasicas
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings("ignore")

#libreria sklearn
#from sklearn.cluster import DBSCAN 
from sklearn.preprocessing import StandardScaler 
from sklearn.preprocessing import normalize 
from sklearn.decomposition import PCA 

# librerias para graficar
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
plt.style.use('seaborn-whitegrid')
plt.rcParams['figure.figsize']=(12, 10)

In [11]:
#carga dataset y exclusion de columnas
df_ud= pd.read_csv("urban-development_chl.csv")#.drop(['id','Unnamed: 32'],axis=1)
df_ud.head(20)

,Country Name,Country ISO3,Year,Indicator Name,Indicator Code,Value
0,#country+name,#country+code,#date+year,#indicator+name,#indicator+code,#indicator+value+num
1,Chile,CHL,2010,Urban land area where elevation is below 5 met...,AG.LND.EL5M.UR.K2,47.12010574
2,Chile,CHL,2000,Urban land area where elevation is below 5 met...,AG.LND.EL5M.UR.K2,47.12010574
3,Chile,CHL,1990,Urban land area where elevation is below 5 met...,AG.LND.EL5M.UR.K2,47.12010574
4,Chile,CHL,2010,Urban land area where elevation is below 5 met...,AG.LND.EL5M.UR.ZS,0.00653134
5,Chile,CHL,2000,Urban land area where elevation is below 5 met...,AG.LND.EL5M.UR.ZS,0.00653134
6,Chile,CHL,1990,Urban land area where elevation is below 5 met...,AG.LND.EL5M.UR.ZS,0.00653134
7,Chile,CHL,2010,Urban land area (sq. km),AG.LND.TOTL.UR.K2,12027.5166
8,Chile,CHL,2000,Urban land area (sq. km),AG.LND.TOTL.UR.K2,12027.5166
9,Chile,CHL,1990,Urban land area (sq. km),AG.LND.TOTL.UR.K2,12027.5166
10,Chile,CHL,2017,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,100
11,Chile,CHL,2016,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,100
12,Chile,CHL,2015,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,99.876858
13,Chile,CHL,2014,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,100
14,Chile,CHL,2013,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,99.8
15,Chile,CHL,2012,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,100
16,Chile,CHL,2011,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,99.856911
17,Chile,CHL,2010,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,99.6494979858398
18,Chile,CHL,2009,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,99.869036
19,Chile,CHL,2008,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,99.5307083129883

In [4]:
df_ud.shape

(563, 6)

In [5]:
df_ud.describe()

,Country Name,Country ISO3,Year,Indicator Name,Indicator Code,Value
count,563,563,563,563,563,563
unique,2,2,60,20,20,492
top,Chile,CHL,2000,Population in urban agglomerations of more tha...,SP.URB.TOTL,100
freq,562,562,17,59,59,4

In [6]:
df_ud.columns

Index(['Country Name', 'Country ISO3', 'Year', 'Indicator Name',
       'Indicator Code', 'Value'],
      dtype='object')

In [13]:
df_ud['Indicator Name'].unique()

array(['#indicator+name',
       'Urban land area where elevation is below 5 meters (sq. km)',
       'Urban land area where elevation is below 5 meters (% of total land area)',
       'Urban land area (sq. km)',
       'Access to electricity, urban (% of urban population)',
       'PM2.5 air pollution, mean annual exposure (micrograms per cubic meter)',
       'PM2.5 air pollution, population exposed to levels exceeding WHO guideline value (% of total)',
       'Population density (people per sq. km of land area)',
       'Urban population living in areas where elevation is below 5 meters (% of total population)',
       'Population living in slums (% of urban population)',
       'Population in largest city',
       'Population in the largest city (% of urban population)',
       'Population in urban agglomerations of more than 1 million',
       'Population in urban agglomerations of more than 1 million (% of total population)',
       'Pump price for diesel fuel (US$ per liter)',
       'Pump price for gasoline (US$ per liter)',
       'Mortality caused by road traffic injury (per 100,000 people)',
       'Urban population growth (annual %)', 'Urban population',
       'Urban population (% of total population)'], dtype=object)

In [12]:
df_in= pd.read_csv("infrastructure_chl.csv")
df_in.head(20)

,Country Name,Country ISO3,Year,Indicator Name,Indicator Code,Value
0,#country+name,#country+code,#date+year,#indicator+name,#indicator+code,#indicator+value+num
1,Chile,CHL,2017,"ICT service exports (BoP, current US$)",BX.GSR.CCIS.CD,351536719.589499
2,Chile,CHL,2016,"ICT service exports (BoP, current US$)",BX.GSR.CCIS.CD,353497985.560915
3,Chile,CHL,2015,"ICT service exports (BoP, current US$)",BX.GSR.CCIS.CD,316447259.910593
4,Chile,CHL,2014,"ICT service exports (BoP, current US$)",BX.GSR.CCIS.CD,342669388.91258
5,Chile,CHL,2013,"ICT service exports (BoP, current US$)",BX.GSR.CCIS.CD,352629578.01145
6,Chile,CHL,2012,"ICT service exports (BoP, current US$)",BX.GSR.CCIS.CD,396182481.843844
7,Chile,CHL,2011,"ICT service exports (BoP, current US$)",BX.GSR.CCIS.CD,339874690.690348
8,Chile,CHL,2010,"ICT service exports (BoP, current US$)",BX.GSR.CCIS.CD,286135584.18796
9,Chile,CHL,2009,"ICT service exports (BoP, current US$)",BX.GSR.CCIS.CD,255242155.975526
10,Chile,CHL,2008,"ICT service exports (BoP, current US$)",BX.GSR.CCIS.CD,303479743.56907
11,Chile,CHL,2007,"ICT service exports (BoP, current US$)",BX.GSR.CCIS.CD,234246828.19637
12,Chile,CHL,2006,"ICT service exports (BoP, current US$)",BX.GSR.CCIS.CD,221644988.70972
13,Chile,CHL,2005,"ICT service exports (BoP, current US$)",BX.GSR.CCIS.CD,233714549.664658
14,Chile,CHL,2004,"ICT service exports (BoP, current US$)",BX.GSR.CCIS.CD,266399208.647847
15,Chile,CHL,2003,"ICT service exports (BoP, current US$)",BX.GSR.CCIS.CD,239723700.831743
16,Chile,CHL,2002,"ICT service exports (BoP, current US$)",BX.GSR.CCIS.CD,224699000
17,Chile,CHL,2001,"ICT service exports (BoP, current US$)",BX.GSR.CCIS.CD,167555856.866015
18,Chile,CHL,2000,"ICT service exports (BoP, current US$)",BX.GSR.CCIS.CD,240700000
19,Chile,CHL,1999,"ICT service exports (BoP, current US$)",BX.GSR.CCIS.CD,212900000